---
title: "Code for figures from HPAanalyze paper"
author:
- name: Anh N. Tran
  affiliation: Northwestern University, Illinois, USA
  email: trannhatanh89@gmail.com
date: 6/18/2019
output: 
    BiocStyle::html_document:
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: true
vignette: >
  %\VignetteIndexEntry{"Code for figures from HPAanalyze paper"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse=TRUE,
  comment="#>",
  warning=FALSE,
  error=FALSE,
  eval=FALSE
)
```

```{r library, message=FALSE, warning=FALSE, error=FALSE}
library(BiocStyle)
library(HPAanalyze)
library(dplyr)
library(ggplot2)
```

```{r}
data <- hpaDownload(downloadList = "histology", 
                    version = "v18")
```


# Figure 2

```{r}
gene_list_2 <- c("TP53", "EGFR", "CD44", "PTEN", "IDH1", "IDH2", "CYCS")

# Panel 2A
tissue_list_2 <- c("skin 1", "cerebellum", "breast")

plot_2a <-
  hpaVisTissue(data = data,
               targetGene = gene_list_2,
               targetTissue = tissue_list_2,
               color = c("#eff3ff", "#bdd7e7","#6baed6", "#2171b5"))

ggsave(filename = "plot_2a.pdf",
       plot = plot_2a,
       device = "pdf")

# Panel 2B
cancer_list_2 <- c("breast cancer", "glioma", "lymphoma", "prostate cancer")

plot_2b <-
  hpaVisPatho(data = data,
              targetGene = gene_list_2,
              targetCancer = cancer_list_2)

ggsave(filename = "plot_2b.pdf",
       plot = plot_2b,
       device = "pdf",
       width = 7,
       height = 5)

# Panel 2C
plot_2c <-
  hpaVisSubcell(data = data,
                targetGene = gene_list_2,
                color = c("white", "black"),
                reliability = c("enhanced", "supported", "approved"))

ggsave(filename = "plot_2c.pdf",
       plot = plot_2c,
       device = "pdf")
```


# Figure 3

```{r}
gene_list_3 <- 
  c("GFAP", "EGFR", "PDGFRA", "PIK3CA", "PTEN", "BRAF", "MDM2", "MDM4", "CDK4")

# Panel 3A
tissue_list_3 <- c("hippocampus", "cerebral cortex")

plot_3a <-
  hpaVisTissue(data = data,
               targetGene = gene_list_3,
               targetTissue = tissue_list_3,
               color = c("#eff3ff", "#bdd7e7","#6baed6", "#2171b5"))

ggsave(filename = "plot_3a.pdf",
       plot = plot_3a,
       device = "pdf",
       width = 7,
       height = 5)

# Panel 3B
plot_3b <-
  hpaVisPatho(data = data,
              targetGene = gene_list_3,
              targetCancer = "glioma")

ggsave(filename = "plot_3b.pdf",
       plot = plot_3b,
       device = "pdf",
       width = 7,
       height = 5)

# Panel 3C
gene_list_3c <- c("PTEN", "H3F3A", "DAXX", "PML")

plot_3c <-
  hpaVisSubcell(data = data,
                targetGene = gene_list_3c,
                color = c("white", "black"),
                reliability = c("enhanced", "supported", "approved"))

ggsave(filename = "plot_3c.pdf",
       plot = plot_3c,
       device = "pdf",
       width = "4",
       height = "3")
```



# Copyright
Anh Tran, 2019

Please cite: __Tran AN, Dussaq AM, Kennell T, Willey C, Hjelmeland A. _HPAanalyze: An R Package that Facilitates the Retrieval and Analysis of The Human Protein Atlas Data_. bioRxiv 355032; doi: https://doi.org/10.1101/355032 __

