###########################
## Visualize tissue data ##
###########################

#' Visualize tissue data
#'
#' Visualize the expression of protein of interest in each target tissue by cell
#' types.
#'
#' @param data Input the list object generated by \code{hpa_download()} or
#'   \code{hpa_subset()}. Require the \code{normal_tissue} dataset.
#' @param target_gene Vector of strings of HGNC gene symbols.
#' @param target_tissue Vector of strings of normal tissues.
#' @param target_cell_type Vector of strings of normal cell types.
#' @param color Vector of 4 colors used to depict different expression levels.
#' @param custom_theme Logical argument. If \code{TRUE}, the function will
#'   return a barebone ggplot2 plot to be customized further.
#'
#' @return This function will return a ggplot2 plot object, which can be further
#'   modified if desirable.
#' 
#' @examples
#'   \dontrun{
#'   downloaded_data <- hpa_download(download_list = 'Normal tissue')
#'   gene_list <- c('TP53', 'EGFR')
#'   tissue_list <- c('breast', 'cerebellum', 'skin 1')
#'
#'   ## A typical function call   
#'   hpa_vis_tissue(data = downloaded_data,
#'                  target_gene = gene_list,
#'                  target_tissue = tissue_list)
#'   
#'   ## With more customization
#'   color_list <- c('white', 'red', 'green', 'blue')
#'   plot <- hpa_vis_tissue(data = downloaded_data,
#'                          target_gene = gene_list,
#'                          target_tissue = tissue_list,
#'                          color = color_list,
#'                          custom_theme = TRUE)
#'   plot + theme_minimal()
#'   }
#'
#' @import dplyr
#' @import ggplot2
#' @export

hpa_vis_tissue <- function(data, 
                           target_gene, 
                           target_tissue, 
                           target_cell_type = NULL,
                           color = c('#ffffb2', '#fecc5c', '#fd8d3c', '#e31a1c'),
                           custom_theme = FALSE) {
    
    ## Just to pass R CMD check
    gene <- tissue <- cell_type <- level <- tissue_cell <- NULL

    plot_data <- data$normal_tissue %>%
        filter(gene %in% target_gene) %>%
        filter(tissue %in% target_tissue)
    
    if(!is.null(target_cell_type)) {
        plot_data <- filter(plot_data, cell_type %in% target_cell_type)
    }
    
    plot_data <- mutate(plot_data,
                        tissue_cell = paste0(tissue, ' / ', cell_type),
                        level = factor(level, levels = c('High', 'Medium', 'Low', 'Not detected')))
    
    level_colors <- c('Not detected' = color[1],
                      'Low' = color[2],
                      'Medium' = color[3],
                      'High' = color[4])
    
    plot <- ggplot(plot_data, aes(x = gene, y = tissue_cell)) +
        geom_tile(aes(fill = level)) +
        scale_x_discrete(limits = target_gene) +
        scale_fill_manual(values = level_colors)
    
    if(!custom_theme) {
        plot <- plot + 
            ylab('Tissue / Cell') +
            xlab('Genes') +
            theme(axis.text.x = element_text(angle = 90, hjust = 1))
    }
    
    return(plot)       
}



##############################
## Visualize pathology data ##
##############################

#' Visualize pathology data
#'
#' Visualize the expression of genes of interest in each cancer.
#'
#' @param data Input the list object generated by \code{hpa_download()} or
#'   \code{hpa_subset()}. Require the \code{pathology} dataset.
#' @param target_gene Vector of strings of HGNC gene symbols.
#' @param target_cancer Vector of strings of normal tissues. The function will
#'   plot all available cancer by default.
#' @param color Vector of 4 colors used to depict different expression levels.
#' @param custom_theme Logical argument. If \code{TRUE}, the function will
#'   return a barebone ggplot2 plot to be customized further.
#'
#' @return This function will return a ggplot2 plot object, which can be further
#'   modified if desirable.
#'
#' @examples
#'   \dontrun{
#'   downloaded_data <- hpa_download(download_list = 'Pathology')
#'   gene_list <- c('TP53', 'EGFR')
#'   cancer_list <- c('breast cancer', 'glioma', 'melanoma')
#'
#'   ## A typical function call
#'   hpa_vis_pathology(data = downloaded_data,
#'                  target_gene = gene_list)
#'
#'   ## With more customization
#'   color_list <- c('yellow', 'red', 'green', 'blue')
#'   plot <- hpa_vis_pathology(data = downloaded_data,
#'                             target_gene = gene_list,
#'                             target_cancer = cancer_list,
#'                             color = color_list,
#'                             custom_theme = TRUE)
#'   plot + theme_minimal()
#'   }
#'
#'
#' @import dplyr
#' @import ggplot2
#' @export

hpa_vis_pathology <- function(data, 
                              target_gene, 
                              target_cancer = NULL, 
                              color = c('#ffffb2', '#fecc5c', '#fd8d3c', '#e31a1c'),
                              custom_theme = FALSE) {
    
    ## Just to pass R CMD check
    gene <- cancer <- high <- medium <- low <- not_detected <- patient_count <- level <- NULL
    
    plot_data <- data$pathology %>%
        filter(gene %in% target_gene)
    
    if(!is.null(target_cancer)) {
        plot_data <- filter(plot_data, cancer %in% target_cancer)
    }
    
    plot_data <- plot_data %>%
        select(gene, cancer, high, medium, low, not_detected) %>%
        rename('High' = 'high', 'Medium' = 'medium', 'Low' = 'low', 'Not detected' = 'not_detected') %>%
        reshape2::melt(measure.vars = c('High', 'Medium', 'Low', 'Not detected'),
                       variable.name = 'level',
                       value.name = 'patient_count')      
    
    level_colors <- c('Not detected' = color[1],
                      'Low' = color[2],
                      'Medium' = color[3],
                      'High' = color[4])
    
    plot <- ggplot(plot_data, aes(x = gene, y = patient_count, fill = level)) +
        geom_bar(stat = 'identity', position = 'fill') +
        scale_x_discrete(limits = target_gene) +
        scale_fill_manual(values = level_colors) +
        facet_wrap(~ cancer)
    
    if(!custom_theme) {
        plot <- plot + 
            ylab('Patient portions') +
            xlab('Genes') +
            theme(axis.text.x = element_text(angle = 90, hjust = 1))
    }
    
    return(plot)       
}


############################
## Visualize subcell data ##
############################

#' Visualize subcellular location data
#' 
#' Visualize the the confirmed subcellular locations of genes of interest.
#' 
#' @param data Input the list object generated by \code{hpa_download()} or
#'   \code{hpa_subset()}. Require the \code{subcellular_location} dataset.
#' @param target_gene Vector of strings of HGNC gene symbols.
#' @param color Vector of 2 colors used to depict if the protein expresses in a
#'   location or not.
#' @param custom_theme Logical argument. If \code{TRUE}, the function will
#'   return a barebone ggplot2 plot to be customized further.
#'
#' @return This function will return a ggplot2 plot object, which can be further
#'   modified if desirable.
#' 
#' @examples
#'   \dontrun{
#'   downloaded_data <- hpa_download(download_list = 'Subcellular location')
#'   gene_list <- c('TP53', 'EGFR', 'CD44', 'PTEN', 'IDH1', 'IDH2', 'CYCS')
#'   
#'   ## A typical function call
#'   hpa_vis_subcell(data = downloaded_data,
#'                   target_gene = gene_list)
#'   
#'   ## With more customization
#'   color_list <- c('white', 'red')
#'   plot <- hpa_vis_subcell(data = downloaded_data,
#'                           target_gene = gene_list,
#'                           color = color_list,
#'                           custom_theme = TRUE)
#'   plot + theme_minimal()
#'   }
#' 
#' 
#' @import dplyr
#' @import ggplot2
#' @export

hpa_vis_subcell <- function(data, 
                            target_gene, 
                            color = c('white', 'black'),
                            custom_theme = FALSE) {
    
    ## Just to pass R CMD check
    gene <- go_id <- NULL
    
    plot_data <- data$subcellular_location %>%
        filter(gene %in% target_gene) %>%
        mutate(location = strsplit(go_id, ';')) %>%
        unnest(location) %>%
        select(location, gene) %>%
        table() %>%
        as.tibble() %>%
        mutate(n = factor(n, levels = c('0', '1')))
    
    level_colors <- c('0' = color[1],
                      '1' = color[2])
    
    plot <- ggplot(plot_data, aes(x = gene, y = location)) +
        geom_tile(aes(fill = n)) +
        scale_x_discrete(limits = target_gene) +
        scale_fill_manual(values = level_colors)
    
    if(!custom_theme) {
        plot <- plot + 
            ylab('Subcellular locations') +
            xlab('Genes') +
            theme(axis.text.x = element_text(angle = 90, hjust = 1))  +
            theme(legend.position="none")
    }
    
    return(plot)       
}


